# This is a basic workflow to help you get started with Actions

name: development-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
          persist-credentials: true
      - name: Build embedQR.js
        run: |
          cpp -undef -P $GITHUB_WORKSPACE/src/embedQR/embedQR.js $GITHUB_WORKSPACE/src/embedQR.js
          chmod +x $GITHUB_WORKSPACE/tools/embedcode.sh
          $GITHUB_WORKSPACE/tools/embedcode.sh $GITHUB_WORKSPACE/src/embedQR.js EMBEDQR $GITHUB_WORKSPACE/src/embedQR.h $GITHUB_WORKSPACE/src/embedQR.gz.h
          chmod -x $GITHUB_WORKSPACE/tools/embedcode.sh
      - name: Build embedQR.engine.js
        run: |
          exit 0
          cpp -undef -P $GITHUB_WORKSPACE/src/jsQR/dist/jsQR.js $GITHUB_WORKSPACE/src/embedQR.engine.js
          chmod +x $GITHUB_WORKSPACE/tools/embedcode.sh
          $GITHUB_WORKSPACE/tools/embedcode.sh $GITHUB_WORKSPACE/src/embedQR.engine.js EMBEDQR_ENGINE $GITHUB_WORKSPACE/src/embedQR.engine.h $GITHUB_WORKSPACE/src/embedQR.engine.gz.h
          chmod -x $GITHUB_WORKSPACE/tools/embedcode.sh
      - name: Copy embedQR.bootstrap.js
        run: cp $GITHUB_WORKSPACE/src/embedQR/embedQR.bootstrap.template.js $GITHUB_WORKSPACE/src/embedQR.bootstrap.template.js
      - name: Copy embedQR.interface.html
        run: cp $GITHUB_WORKSPACE/src/embedQR/embedQR.interface.template.html $GITHUB_WORKSPACE/src/embedQR.interface.template.html

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test
        run: exit 0
        
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Commit and push build
        uses: resmh/push@master-pushdist
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'development'
          cherrypickbranch: 'development-dist'
#  deploy-dist:
#    runs-on: self-hosted
#    needs: deploy
#    steps:
#      - name: Switch to development-dist
#        uses: actions/checkout@v2
#        with:
#          ref: 'development-dist'
#          fetch-depth: 0
 #         persist-credentials: false
 #     - name: Checkout distribution files
 #       run: |
 #         git checkout development -- embedQR.js
 #         git checkout development -- embedQR.h
 #         git checkout development -- embedQR.gz.h
 #         git checkout development -- embedQR.engine.js
 #         git checkout development -- embedQR.engine.h
 #         git checkout development -- embedQR.engine.gz.h
 #         git checkout development -- embedQR.bootstrap.template.js
 #         git checkout development -- embedQR.interface.template.html
 #     - name: Commit and push build
 #       uses: actions-js/push@master
 #       with:
 #         github_token: ${{ secrets.GITHUB_TOKEN }}
 #         branch: 'development-dist'
