# This is a basic workflow to help you get started with Actions

name: development-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
          persist-credentials: false
      - name: Build embedQR.js
        run: |
          cpp -undef -P $GITHUB_WORKSPACE/src/embedQR/embedQR.js $GITHUB_WORKSPACE/src/embedQR.js
          chmod +x $GITHUB_WORKSPACE/tools/embedcode.sh
          $GITHUB_WORKSPACE/tools/embedcode.sh $GITHUB_WORKSPACE/src/embedQR.js EMBEDQR $GITHUB_WORKSPACE/src/embedQR.h $GITHUB_WORKSPACE/src/embedQR.gz.h
          chmod -x $GITHUB_WORKSPACE/tools/embedcode.sh
      - name: Build embedQR.engine.js
        run: |
          cpp -undef -P $GITHUB_WORKSPACE/src/jsQR/dist/jsQR.js $GITHUB_WORKSPACE/src/embedQR.engine.js
          chmod +x $GITHUB_WORKSPACE/tools/embedcode.sh
          $GITHUB_WORKSPACE/tools/embedcode.sh $GITHUB_WORKSPACE/src/embedQR.engine.js EMBEDQR_ENGINE $GITHUB_WORKSPACE/src/embedQR.engine.h $GITHUB_WORKSPACE/src/embedQR.engine.gz.h
          chmod -x $GITHUB_WORKSPACE/tools/embedcode.sh
      - name: Copy embedQR.bootstrap.js
        run: cp $GITHUB_WORKSPACE/src/embedQR/embedQR.bootstrap.template.js $GITHUB_WORKSPACE/src/embedQR.bootstrap.template.js
      - name: Copy embedQR.interface.html
        run: cp $GITHUB_WORKSPACE/src/embedQR/embedQR.interface.template.html $GITHUB_WORKSPACE/src/embedQR.interface.template.html
      - name: Commit and push build
        uses: resmh/push@master-pushdist
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'development'
          distbranch: 'development-dist'
          distfiles: 'README.md:LICENSE.md:LICENSE.engine.md:src/embedQR.js:src/embedQR.h:src/embedQR.gz.h:src/embedQR.engine.js:src/embedQR.engine.h:src/embedQR.engine.gz.h:src/embedQR.bootstrap.template.js:src/embedQR.interface.template.html:extra/embedQR.interface.capwarn.template.html:extra/embedQR.interface.capwarn.template.h'
